#!/bin/bash
echo "Enter the value:"
read num

if [ $num -gt 7 ]
then
echo " $num is greater than 7 "

elif [ $num -eq 7 ]
then
echo " $num is equal to 7 "

elif [ $num -lt 7 ]
then
echo " $num is lesser than 7 "

else
echo " Entered value is wrong and its not a integer value "
fi
