#!/bin/bash

echo "Enter the path"
read path

if [ -f $path ]
then
echo " $path is file "

elif [ -d $path ]
then
echo " $path id Directory "

elif [ -l $path ]
then
echo " $path is a link "

else
echo " $path does not exist "
fi
